### ISSUE TITLE
Tree functionality

### ISSUE THREAD

**Issue by atotic** [Polymer/core-menu#12]
I've been trying to use core-menu/core-submenu as a tree, and there are many problems. Before I start an elaborate writeup, I'd like an see to know
- Is using core-menu as a tree part of intended functionality or not?
- If not, are you planning on core-tree?

My suggestion is to add a tree property to core menu, and make it work. Tree is visually identical, only behavior differs.

**Comment by wmleler** [comment]
I'm in the middle of writing a component for a tree menu for a project I'm working on. Here's what I have so far. I'm new to Polymer, so I'd appreciate feedback and suggestions.
:::: tree-node.html ::::
<link rel="import" href="../bower_components/polymer/polymer.html">

<polymer-element class="menu" name="tree-node" attributes="nodeData path">
  <template>
    <link rel="stylesheet" href="tree-node.css">
    <ul>
      <li>
        <template if="{{nodeData.children.length>0}}">
          <core-icon id="widget" icon="add-circle" on-tap="{{openme}}"></core-icon>
        </template>
        <span class="item {{nodeData.children.length>0?'':'noChildren'}}" on-tap="{{activate}}">
          <core-icon class="dicon" icon="{{iconTable[nodeData.kind]}}"></core-icon>
          {{nodeData.name}}
        </span>
      </li>
      <template if="{{nodeData.opened}}" repeat="{{child in nodeData.children}}">
        <tree-node nodeData="{{child}}" path="{{path+'/'+nodeData.name}}"></tree-node>
      </template>
    </ul>
  </template>
  <script>

  Polymer('tree-node', {
    created: function() {
      this.path = this.path || '/';
    },
    openme: function() {
      this.$.widget.icon = this.nodeData.opened ? 'add-circle' : 'arrow-drop-down-circle';
      this.nodeData.opened = !this.nodeData.opened;
    },
    activate: function(event, detail, sender) {
      var els = document.querySelectorAll('tree-node /deep/ span.item.active');
      for (var i = 0; i < els.length; i++) {
        els[i].classList.remove('active');
      }
      sender.classList.add('active');
      console.log(this.path+'/'+this.nodeData.name);
    },
    iconTable: {
      namespace: 'dns',
      label: 'folder',
      service: 'label-outline'
    }
  });
  </script>
</polymer-element>
:::: tree-node.css ::::
ul {
  list-style-type: none;
  padding: 0;
  margin: 3px 0 0 20px;
  font-size: 18px;
}
ul li {}
#widget {
  width: 25px;
  height: 25px;
  padding-right: 4px;
}
span.item {
  padding: 1px 5px 2px 0;
  border: solid black 1px;
  border-radius: 5px;
  position: relative;
}
span.item.noChildren {
  left: 34px;
}
span.item.active {
  border: inset #ddd 3px;
  font-weight: bold;
}
span.item.active::after {
  content: " \0025B6";
}
core-icon {
  margin-bottom: 5px;
}
:::: index.html ::::
<!DOCTYPE html>
<html><head>
  <title>Namespace tree menu</title>
  <script src="bower_components/webcomponentsjs/webcomponents.js"></script>
  <link rel="import" href="bower_components/core-icons/core-icons.html">
  <link rel="import" href="elements/tree-node.html">
  <style>
    body {
      font-family: sans-serif;
    }
  </style>
</head>
<body>

  <h2>Tree Menu</h2>
  <section><tree-node id="menu"></tree-node></section>

<script>
  var treeNode = document.getElementById('menu');
  treeNode.nodeData = {
    name: 'root', kind: 'namespace', children: [
      { name: 'lib', kind: 'service'},
      { name: 'users', kind: 'label', children: [
        { name: 'local', kind: 'namespace', children: [
          { name: 'george', kind: 'service'},
          { name: 'martha', kind: 'service'}
        ]},
      { name: 'remote', kind: 'namespace'}
      ]}
    ]
  };
</script>
</body></html>

And here is what it looks like:
![screen shot 2015-01-02 at 2 06 16 pm](https://cloud.githubusercontent.com/assets/50357/5600110/93a89ad2-9288-11e4-85fd-edad767a4701.png)

**Comment by sup3rb0wlz** [comment]
check out my element nb-menu   It takes a piece of JSON and makes a core-menu core-submenu, core-item tree out of it.
